### ISSUE TITLE
Update tokio and related dependencies

### ISSUE THREAD

**Issue by liwp** [get-eventually/eventually-rs#154]
**Is your feature request related to a problem? Please describe.**

`eventually-rs` (and friends) depend on `tokio` 0.2.0, but 1.0.0 was released in January, and 1.3.0 was released yesterday. We use 1.x in our project already, so I'm nervous about pulling in `eventually-rs` and introducing `tokio` 0.2.0 into our dependencies in case `tokio` 1.x and 0.2.0 conflict in some way.

I'm not (yet) familiar enough with `tokio` or `eventually-rs` to know what the potential issues might be in mixing different `tokio` versions.

**Describe the solution you'd like**

Update the `tokio` dependencies to 1.0+ so at least we're on the same `tokio` major version. I appreciate `tokio` moves fast and chasing the bleeding edge isn't beneficial to anyone.

This also applies to other `tokio`-related dependencies like `bb8` and `tokio-postgres`, I suppose.

**Describe alternatives you've considered**

Our project depends on `tokio` 1.2.0 (and `tokio-postgres` 0.7.0 and `bb8-postgres` 0.7.0`) already. I suppose we could downgrade to 0.2.0.

**Comment by ar3s3ru** [comment]
Hello @liwp,
Thank you for opening the issue!

This will be fixed in #155, and planning on releasing `v0.4.1` for that 👍🏻 

Hope you enjoy `eventually-rs` for your project!
And stay tuned for [`v0.5.0`](https://github.com/eventually-rs/eventually-rs/pull/140) 😉

**Comment by liwp** [comment]
Hi @ar3s3ru , thanks for the quick response!

Turns out that a bigger issue for me ended up being an out-of-date version of `refinery` in `enentually-postgres`: looks like `refinery` used a non-public feature of `serde` that has been removed in one of the recent minor version bumps, and as a result `refinery` doesn't even build. This has been addressed in `refinery` `0.5.0`, I think. I was able to build a local version of `eventually-postgres` with `0.5.0` of `refinery` so it should be just a question of updating `Cargo.toml`.

Other 'issues' that we hit while trying to start using `eventually` in an existing project:

-  `eventually-postgres` running its own DB migrations collides with our existing migrations and won't apply. As a workaround I can point `eventually` to a different DB in postgres.
- `eventually-postgres` uses stored procs, which are not supported in cockroach DB, which is what we're deploying with (granted, nowhere does it say `eventually-postgres` should work with Cockroach :slightly_smiling_face: )
- the `bb8` connection pool support hasn't been released yet

I would suggest considering removing the use of refinery: providing the SQL files and letting the user manage their DB migration themselves, I think, would make things more flexible :shrug: 

As a result we've decided to not use `eventually` in this case. I think we would've had a better time with it if we'd started the project with eventually right from the start, but we're new to CQRS and ES, and are trying to just dip our toes in at this stage.

**Comment by ar3s3ru** [comment]
Hey @liwp,

Thanks for the answer, always love when I get constructive feedback ❤️  

>Turns out that a bigger issue for me ended up being an out-of-date version of refinery in enentually-postgres: looks like refinery used a non-public feature of serde that has been removed in one of the recent minor version bumps, and as a result refinery doesn't even build. This has been addressed in refinery 0.5.0, I think. I was able to build a local version of eventually-postgres with 0.5.0 of refinery so it should be just a question of updating Cargo.toml.

This issue should be fixed on master now, updated the `refinery` version with #155 👍🏻 

>eventually-postgres running its own DB migrations collides with our existing migrations and won't apply. As a workaround I can point eventually to a different DB in postgres.

Yes, this is a bit unfortunate, but I assume this is only happening if you're using `refinery` for your migrations. Is that the case?

In general, it's a good idea to keep databases separate (by using `CREATE DATABASE`) to ensure nobody messes with the event store (which should be where your data, and your money, is). But keeping a single database is a very valid point, will try to solve this issue in the next release 👍🏻 

>eventually-postgres uses stored procs, which are not supported in cockroach DB, which is what we're deploying with (granted, nowhere does it say eventually-postgres should work with Cockroach slightly_smiling_face )

Oh, that's unfortunate 😞   
Well, if you feel like giving a try to implement the Event Store for Cockroach, I'd love to review and merge the code 🥳 

>the bb8 connection pool support hasn't been released yet

If you refer to accessing the `tokio_postgres::Connection`, I wouldn't hold my breath on that (for good reasons) 😅  
Anyway, I'm planning to give [`sqlx`](https://docs.rs/sqlx/0.5.1/sqlx/index.html) a try, given how big it's becoming in the ecosystem. It might solve different issues, one of which is the connection pooling 👍🏻 

>I would suggest considering removing the use of refinery: providing the SQL files and letting the user manage their DB migration themselves, I think, would make things more flexible shrug

This is a valuable idea, definitely worth exploring. My rationale behind migrate the database using `refinery` is to **ensure** that, if an `eventually_postgres::EventStore` instance is obtained, it would be a **valid** instance -- database and all.

>As a result we've decided to not use eventually in this case. I think we would've had a better time with it if we'd started the project with eventually right from the start, but we're new to CQRS and ES, and are trying to just dip our toes in at this stage.

Totally understandable, after all the library is still unstable, and with `v0.5.0` planned breaking changes it's not a decision to take lightly for pre-existing projects. If you feel like trying it out in a personal pet project and have additional feedback, feel free to post here or reach out in [our Discord server](https://discord.gg/yww3mXHbRF) 😄

**Comment by liwp** [comment]
> > eventually-postgres running its own DB migrations collides with our existing migrations and won't apply. As a workaround I can point eventually to a different DB in postgres.
> 
> Yes, this is a bit unfortunate, but I assume this is only happening if you're using `refinery` for your migrations. Is that the case?

Yes that's right, we have existing `refinery` migrations in the project to `refinery` gets upset when it sees multiple migrations with the same version number.
 
Anyhow, thanks for all your work on the project, I think it's a nice library and I'm sure to come back to it at some point in the future!

**Comment by rbuckland** [comment]
I assume this issue can be closed now

**Comment by ar3s3ru** [comment]
@rbuckland the issue has been fixed on latest master branch, but I haven't created a release on crates.io yet, that's why I kept it open. I will close it now and open a new issue for releasing the next version 👍🏻
