### ISSUE TITLE
move example app into repo

### ISSUE THREAD

**Issue by danieleades** [get-eventually/eventually-rs#171]
is it possible to move the example app into the repo? this will ensure that the example always stays aligned with the current API

**Comment by ar3s3ru** [comment]
Previously that was the case: the app was part of the repo. However, at some point the dependencies for the example app broke, and it completely broke compilation of the project (due to the virtual workspace/monorepo).

I've decided to take it out so that I could continue work on the main library, but I wouldn't mind bringing back in here. I did (and do) not have much time to find out why it broke and update the dependencies though...

**Comment by danieleades** [comment]
> I did (and do) not have much time to find out why it broke and update the dependencies though

i could perhaps take a look? I might get some time in the next few days. Some of the dependencies in that project are pretty old, old enough that you *could* be running into a `Future` compat issue.

**Comment by danieleades** [comment]
the issue is with an outdated dependency in `eventually-postgres`

specifically, `refinery-core` relies on a module in serde which used to be public, but is now private. I guess that should have been marked as a breaking change, but wasn't (or the dependency resolution would pick it up instead of the compiler)

```
error[E0603]: module `export` is private
   --> ...../.cargo/registry/src/github.com-1ecc6299db9ec823/refinery-core-0.3.2/src/runner.rs:11:12
    |
11  | use serde::export::Formatter;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> ...../.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
refinery-core v0.3.2
├── refinery v0.3.0
│   └── eventually-postgres v0.2.0
│       └── eventually v0.4.0
│           └── eventually-app-example v0.1.0 (/home/dan/Code/rust/eventually-app-example)
└── refinery-macros v0.3.0 (proc-macro)
    └── refinery v0.3.0 (*)
```

I think the solution is to release `eventually` 0.4.1 with `eventually-postgres 0.3.0` (which bumps the `refinery` dependency from 0.3.0 to 0.6.0)

**Comment by danieleades** [comment]
might be worth starting a discussion what topology this repo *should* have (with respect to the various packages in the workspace)

**Comment by ar3s3ru** [comment]
> I think the solution is to release `eventually` 0.4.1 with `eventually-postgres 0.3.0` (which bumps the `refinery` dependency from 0.3.0 to 0.6.0)

Now that we've merged some breaking changes on `master`, it becomes a bit more difficult to release anything. At this point I'd rather try to work as much as possible towards `0.5.0` and release that one instead.

As for the app, I think it'd be nice to move it back inside the repo if https://github.com/get-eventually/eventually-app-example/pull/2 allows us to. Wdyt?

**Comment by ar3s3ru** [comment]
Closing this one as the app example has been moved in the repo already 👍🏻
