### ISSUE TITLE
Codecov upload is broken

### ISSUE THREAD

**Issue by danieleades** [get-eventually/eventually-rs#172]
the codecov upload job in CI is failing

```
{'detail': ErrorDetail(string='Could not find a repository, try using upload token', code='not_found')}
404
==> Uploading to Codecov
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12383  100   103  100 12280    528  62974 --:--:-- --:--:-- --:--:-- 63502
    {'detail': ErrorDetail(string='Could not find a repository, try using upload token', code='not_found')}
```

**Comment by danieleades** [comment]
possible the repo is simply not registered on codecov?
i've tried updating the action in #173 but that doesn't help

should probably update the action *anyway* though, since the old version has a security issue.

**Comment by ar3s3ru** [comment]
Oh, this is probably because I've renamed the organization to a different name... I will take care of it 👍🏻

**Comment by danieleades** [comment]
> Oh, this is probably because I've renamed the organization to a different name... I will take care of it 👍🏻

i think i've got some rebasing to do on the open pull requests. do you want to ping me when the codecov is working again? I'll hold off on that before updating the PRs

**Comment by ar3s3ru** [comment]
It's working now, closing it ✌🏻
