### ISSUE TITLE
issue with dependabot configuration

### ISSUE THREAD

**Issue by danieleades** [get-eventually/eventually-rs#178]
Is there some issue with the dependabot configuration in this repo?

if i enable dependabot on my fork, i get a few pull request relating to the outdated github actions - https://github.com/danieleades/eventually-rs/pulls

i don't see any matching dependabot pull requests on your repo. in fact there's none at all since October 2020 - https://github.com/get-eventually/eventually-rs/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+

perhaps it just needs to be re-enabled since you moved to an "organisation"

**Comment by ar3s3ru** [comment]
Thanks for opening the issue, I just re-enabled it 👍🏻
