### ISSUE TITLE
Add more subslicing operations for EventStore::stream

### ISSUE THREAD

**Issue by ar3s3ru** [get-eventually/eventually-rs#49]
As of now, `EventStore` only allows to get a slice of the Event Stream (persisted events) from the head.

Let's say we have these events (with offset):
```
stream: [ (A, 1), (B, 2), (C, 2), (D, 3), (C, 3), (A, 4) ]
```

With the current signature, we can only do this:
```
store.stream(id, 0) -> [ (A, 1), (B, 2), (C, 2), (D, 3), (C, 3), (A, 4) ]
store.stream(id, 2) -> [ (B, 2), (C, 2), (D, 3), (C, 3), (A, 4) ]
store.stream(id, 4) -> [ (A, 4) ]
```

However, it might be useful to get a different slice of the Event Stream:
```
store.stream(id, to: 3)          -> [ (A, 1), (B, 2), (C, 2), (D, 3), (C, 3) ]
store.stream(id, from: 3, to: 4) -> [ (D, 3), (C, 3), (A, 4) ]
```

This might be extremely useful for Snapshots, where the Snapshot Projector would need to get a slice of the events to rebuild the State and store it for optimized access.

## Proposal

Change the `EventStore::stream` signature to the following:
```rust
fn stream(&self, id: Self::SourceId, op: Fetching<Self::Offset>)
    -> BoxFuture<EventStream<Self>, Self::Error>;
```

where `Select` is the selecting criteria for the `EventStream` result:
```rust
pub enum Select<T: Copy + PartialOrd + Ord + Sized> {
    All,
    From(T),
    To(T),
    Slice(T, T),
}
```

so that we can use it as following:
```rust
store.stream(id, Select::All)         -> [ (A, 1), (B, 2), (C, 2), (D, 3), (C, 3), (A, 4) ]
store.stream(id, Select::From(2))     -> [ (B, 2), (C, 2), (D, 3), (C, 3), (A, 4) ]
store.stream(id, Select::To(2))       -> [ (A, 1), (B, 2), (C, 2) ]
store.stream(id, Select::Slice(2, 3)) -> [ (B, 2), (C, 2), (D, 3), (C, 3) ]
```

**Comment by danieleades** [comment]
you might be reinventing [`std::ops::RangeBounds`](https://doc.rust-lang.org/std/ops/trait.RangeBounds.html) there ...

| Select | Range |
|--------|--------|
|All        | .. |
|From(T) | a.. |
| To(T) | ..b |
|Slice(T, T) | a..b |

your signature would then be something like

```rust
async fn stream(
    &self, id: Self::SourceId,
    range: impl RangeBounds<T>
) -> Result<EventStream<Self>, Self::Error>;
```
(where `T: Ord`)

**Comment by ar3s3ru** [comment]
Oh this is great, thanks for pointing it out!

For now I don't think we ever need anything other than `Stream::All` and `Stream::From(T)`, but it's good to keep in mind there is already a type for this 👍🏻 

I will keep the issue open for the time being.

**Comment by ar3s3ru** [comment]
On further thought, I don't think we'll ever need more than `All` and `From(T)`.

`All` is typically useful for rebuilding the whole state of an Aggregate.

`From(T)` is useful when rebuilding the state using Snapshots.

The idea is always to open an Event Stream (or a `Stream<T>`) and consume it. Thus, the other operations specified from `std::ops::RangeBounds` are not necessary and would actually introduce unneeded complexity.

I'm gonna close this issue for now, if the need for this comes up in the future we can always reopen it :v:

**Comment by danieleades** [comment]
> On further thought, I don't think we'll ever need more than `All` and `From(T)`.
> 
> `All` is typically useful for rebuilding the whole state of an Aggregate.
> 
> `From(T)` is useful when rebuilding the state using Snapshots.
> 
> The idea is always to open an Event Stream (or a `Stream<T>`) and consume it. Thus, the other operations specified from `std::ops::RangeBounds` are not necessary and would actually introduce unneeded complexity.
> 
> I'm gonna close this issue for now, if the need for this comes up in the future we can always reopen it :v:

You might need this for time travel?

I'm speculating though

**Comment by ar3s3ru** [comment]
Time travel works on timestamps, but `version` and `sequence_number` have no concept of time. The only way to implement it properly is to `filter` the `Stream<Persisted<T>>` returned by the EventStore or the Subscription 👀
